import assert from 'node:assert/strict';
import {build} from 'vite';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
await build({configFile:false,logLevel:'error',build:{outDir:'.sites-runtime/agenda-unit',emptyOutDir:true,minify:false,lib:{entry:resolve('lib/agenda.ts'),formats:['es'],fileName:'planner-agenda'}}});
const {agendaActivities,agendaFromUrl}=await import(pathToFileURL(resolve('.sites-runtime/agenda-unit/planner-agenda.js')).href);
const state={selections:{},pending:{},revision:0,budgetMode:'flights'};
const id=slot=>`wpt-wynn-2026/W01/${slot}`;
const pass=name=>console.log('PASS',name);
const original=agendaActivities(state),supplement=agendaActivities(state,true);
assert.equal(original.length,125);assert.equal(original.filter(x=>x.kind==='start').length,102);assert.equal(supplement.length,136);assert.equal(new Set(supplement.map(x=>x.id)).size,136);pass('102 starts + 23 continuation activities; 11 opt-in satellites; unique identities');
state.selections[id('R0')]={status:'attend',version:1};state.selections[id('R3')]={status:'attend',version:1};
let activities=agendaActivities(state),next=activities.filter(x=>x.event.id==='W01'&&x.kind==='continuation');
assert.equal(next.length,1);assert.equal(next[0].status,'attend');assert.equal(next[0].buyin,0);assert.equal(next[0].date,'2026-11-30');assert.equal(activities.find(x=>x.id===id('R4')).status,'undecided');pass('multiple attending flights yield one conditional continuation and no extra buy-in');
state.selections[id('R0')].status='skip';state.selections[id('R3')].status='watch';
assert.equal(agendaActivities(state).find(x=>x.event.id==='W01'&&x.kind==='continuation').status,'watch');pass('watch follows to continuation after attendance is removed');
state.selections[id('R3')].status='skip';
assert.equal(agendaActivities(state).find(x=>x.event.id==='W01'&&x.kind==='continuation').status,'undecided');
for(const slot of ['R4','R6','R7','R8'])state.selections[id(slot)]={status:'skip',version:1};
assert.equal(agendaActivities(state).find(x=>x.event.id==='W01'&&x.kind==='continuation').status,'skip');pass('continuation excluded only when every starting flight is excluded');
state.pending.W01={status:'attend',version:1};
assert.equal(agendaActivities(state).find(x=>x.event.id==='W01'&&x.kind==='continuation').status,'attend');pass('legacy unassigned attendance remains represented in the agenda');
globalThis.window={location:{hash:'#view=schedule&day=2026-12-21&agendaStatuses=attend,watch&continuations=no'}};
assert.deepEqual(agendaFromUrl(),{view:'schedule',day:'2026-12-21',statuses:['attend','watch'],continuations:false,month:'2026-12'});
window.location.hash='#view=invalid&day=2026-12-22&agendaStatuses=invalid&month=2030-01';
assert.deepEqual(agendaFromUrl(),{view:'discover',day:'',statuses:[],continuations:true,month:'2026-11'});pass('route restores valid day and month; rejects out-of-festival dates and invalid categories');
