import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const out=resolve('.sites-runtime/qa/jeju');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:950},offline:true,reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(15000);
const data=JSON.parse(await fs.readFile('lib/jeju-poker-festival-2026.json','utf8')),series='jeju-poker-festival-2026',file=pathToFileURL(resolve('release/WPT赛事自选表.html')).href;
const errors=[],requests=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});const pass=s=>{checks.push(s);console.log('PASS',s);};
const id=(n,i=0)=>`${series}/JPF-${n}/${data.find(e=>e.id==='JPF-'+n).starts[i].id}`;
const row=(n,i=0)=>page.locator(`.mobile-event[data-entry-id="${id(n,i)}"]`);
const select=async(label,value)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click();};
const nav=name=>page.locator('.bottom-nav').getByRole('button',{name:name==='我的自选'?/我的自选/:name,exact:true}).click();
const search=text=>page.getByRole('textbox',{name:'搜索赛事',exact:true}).fill(text);
const choose=(n,i=0)=>row(n,i).locator('.class-option').filter({hasText:/^参加$/}).click();
const closeCart=async()=>{await page.getByRole('button',{name:'关闭我的自选',exact:true}).click();await page.locator('.cart-sheet').waitFor({state:'hidden'});};
const discover=async()=>{await nav('赛事');await page.getByRole('link',{name:'查看 Jeju Poker Festival 2026 完整赛程',exact:true}).click();};
try{
 await page.goto(file+'#view=home&region=apac');assert.equal(await page.locator('.festival-card').count(),2);const card=page.locator(`[data-series-id="${series}"]`);await card.click();
 assert.match(await page.locator('.results-bar').innerText(),/160.*140/s);assert.match(await page.locator('.series-header').innerText(),/韩国.*KST/s);assert.equal(await page.locator('.series-header img').evaluate(e=>e.complete&&e.naturalWidth>0),true);
 assert.match(await row(3).innerText(),/₩1,300,000（≈¥6,445.40）/);assert.match(await row(1).innerText(),/报名\s+未公布/);assert.doesNotMatch(await row(1).innerText(),/₩0/);
 await choose(1);await nav('我的自选');assert.match(await page.locator('.cart-budget').innerText(),/1 个买入报名费未公布/);assert.equal(await page.locator('.cart-budget [data-currency]').count(),0);await closeCart();
 await search('KPC MAIN EVENT');await choose(3);await choose(3,1);await search('JPF-79');await choose(79);await row(79).locator('.event-title').click();assert.match(await row(79).innerText(),/Day 2 第 14 级/);assert.match(await row(79).innerText(),/\$8,000/);
 pass('Jeju APAC card opens 160 starts, original KRW/USD prices, real local branding and honest unknown buy-in without a zero budget');
 await search('');await select('报名费筛选','$8,000 及以下');assert.equal(await page.locator('.mobile-event').count(),1);assert.ok(page.url().includes('USD%3A8000'));await page.reload();await row(79).waitFor();
 await select('报名费筛选','₩50万及以下');assert.equal(await row(79).count(),0);assert.equal(await row(1).count(),0);await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 await select('保底筛选','₩18亿及以上');assert.equal(await page.locator('.mobile-event').count(),4);await page.getByRole('button',{name:'重置筛选',exact:true}).click();await select('赛事类型','卫星赛');assert.match(await page.locator('.results-bar').innerText(),/17.*17/s);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await search('JPF-32');assert.match(await row(32).innerText(),/11\/01 · 00:00/);await row(32).locator('.event-title').click();assert.match(await row(32).innerText(),/2026-10-31 24:00/);
 await search('JPF-104');await row(104).locator('.event-title').click();assert.match(await row(104).innerText(),/₩4,500,000/);assert.match(await row(104).innerText(),/2,000,000 KRW.*包含/s);
 pass('currency-scoped filters survive reload, guarantees and satellites match source, midnight rows cross to the correct day and bounty is not charged twice');
 await nav('我的日程');assert.equal(await page.locator('.agenda-row').count(),7);assert.match(await page.locator('.schedule-calendar-top').innerText(),/10\/28.*11\/11.*KST/);
 await page.getByRole('button',{name:'下个月',exact:true}).click();await page.getByRole('button',{name:/2026年11月1日 星期日/}).click();assert.equal(await page.locator('.agenda-row').count(),1);assert.match(await page.locator('.agenda-row').innerText(),/晋级/);await page.reload();assert.ok(page.url().includes('day=2026-11-01'));
 await page.screenshot({path:resolve(out,'agenda-390.png')});
 await discover();await select('赛事系列','WPT · Wynn 2026');await page.locator('.mobile-event').first().locator('.class-option').filter({hasText:/^参加$/}).click();await nav('我的自选');
 assert.match(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),/₩2,600,000/);assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/\$8,600/);assert.match(await page.locator('.cart-budget').innerText(),/1 个买入报名费未公布/);
 await select('预算计算方式','同一赛事只算一次');assert.match(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),/₩1,300,000/);await closeCart();
 pass('cross-month selected-only agenda deduplicates continuations and mixed-series budgets keep USD/KRW separate in both modes');
 await nav('我的');await select('显示货币','韩元 · KRW');await discover();await search('KPC MAIN EVENT');assert.equal(await row(3).locator('.converted-price').count(),0);
 await nav('我的');await page.getByRole('button',{name:/管理后台/}).click();assert.equal(await page.getByRole('textbox',{name:'韩元汇率',exact:true}).inputValue(),'4.958');await page.getByRole('textbox',{name:'韩元汇率',exact:true}).fill('5');await page.getByRole('button',{name:'保存汇率',exact:true}).click();
 await page.getByRole('tab',{name:'赛事管理',exact:true}).click();await page.getByRole('textbox',{name:'搜索管理赛事',exact:true}).fill('SUPER U CHALLENGE');await page.locator('.admin-event-row').click();assert.match(await page.locator('.event-editor-sheet').innerText(),/统一报名费 · USD/);await page.getByRole('button',{name:'关闭赛事编辑',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await page.getByRole('textbox',{name:'搜索管理赛事',exact:true}).fill('JPF ANNUAL');await page.locator('.admin-event-row').click();assert.equal(await page.getByLabel('赛事报名费',{exact:true}).inputValue(),'');await page.getByLabel('赛事报名费',{exact:true}).fill('100000');await page.getByRole('button',{name:'保存赛事',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await nav('我的');await select('显示货币','人民币 · CNY');await discover();await search('JPF ANNUAL');assert.match(await row(1).innerText(),/₩100,000（≈¥500.00）/);
 const pending=page.waitForEvent('download');await page.getByRole('link',{name:/下载原始赛程 PDF/}).click();const pdfPath=resolve(out,'download.pdf');await(await pending).saveAs(pdfPath);
 const hash=b=>createHash('sha256').update(b).digest('hex');assert.equal(hash(await fs.readFile(pdfPath)),hash(await fs.readFile('sources/jeju-poker-festival-2026.pdf')));
 pass('KRW display preference and editable rate work, USD admin labels stay correct, missing fee can be supplied, PDF downloads byte-for-byte offline');
 await search('PL BIG O FANATIC');await choose(68);await nav('我的日程');await page.getByRole('button',{name:'全部日期',exact:true}).click();await page.locator(`[data-activity-id="${series}/JPF-68/continuation/0"]`).click();assert.match(await page.locator('.agenda-detail-sheet .detail').innerText(),/盲注级别\s+原表未列/);await page.getByRole('button',{name:'关闭比赛详情',exact:true}).click();await page.locator('.agenda-detail-sheet').waitFor({state:'hidden'});await discover();
 pass('a final-day blind duration absent from the PDF is not inferred from Day 1');
 await search('');await page.getByRole('button',{name:'重置筛选',exact:true}).click();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:950});await page.evaluate(()=>window.scrollTo(0,0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:resolve(out,`discovery-${width}.png`)});}
 await page.setViewportSize({width:320,height:950});await page.getByRole('combobox',{name:'报名费筛选',exact:true}).click();const popup=await page.locator('.filter-popup').boundingBox();assert.ok(popup.x>=0&&popup.x+popup.width<=320);assert.ok((await page.getByRole('option',{name:'₩100万及以下',exact:true}).boundingBox()).height<=44);await page.screenshot({path:resolve(out,'filter-320.png')});await page.keyboard.press('Escape');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);pass('phone/desktop layouts and all Jeju flows remain entirely offline without browser errors');
}finally{await page.screenshot({path:resolve(out,'last-state.png')});await fs.writeFile(resolve(out,'results.json'),JSON.stringify({checks,errors,requests},null,2));await browser.close();}
