import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {chromium} from 'playwright';

const output=resolve('.sites-runtime/qa/kpc');await fs.mkdir(output,{recursive:true});
const data=JSON.parse(await fs.readFile('lib/kpc-jeju-2026.json','utf8'));
const series='kpc-jeju-2026';
const official=number=>{const event=data.find(item=>item.officialNumber===number);assert.ok(event,`official KPC event #${number}`);return event;};
const opening=official(1),main=official(8),usdEvent=official(3);
// These anchors were checked against the official public schedule, independently of the imported fixture.
assert.equal(data.length,73);assert.equal(data.flatMap(event=>event.starts).length,86);assert.equal(data.flatMap(event=>event.continuations).length,15);
assert.equal(main.title,'KPC MAIN EVENT');assert.equal(main.currency,'KRW');assert.equal(main.buyin,1300000);assert.equal(main.guarantee,880000000);
assert.equal(main.starts.length,6);assert.equal(main.continuations.length,2);
assert.deepEqual(main.starts.slice(0,2).map(slot=>[slot.date,slot.hour]),[['2026-10-11',13.5],['2026-10-12',12]]);
assert.deepEqual(main.continuations.map(slot=>[slot.date,slot.hour]),[['2026-10-15',12],['2026-10-16',13]]);
assert.equal(opening.buyin,800000);assert.equal(opening.starts[0].registrationCloses,'2026-10-10T15:25');
assert.equal(usdEvent.currency,'USD');assert.equal(usdEvent.buyin,5000);assert.equal(usdEvent.starts[0].hour,12.5);
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:950},offline:true,reducedMotion:'reduce'});
const page=await context.newPage(),checks=[],errors=[],requests=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(/^https?:/.test(request.url()))requests.push(request.url());});
const pass=name=>{checks.push(name);console.log('PASS',name);};
const file=pathToFileURL(resolve('release/WPT赛事自选表.html')).href;
const entry=(event,index=0)=>`${series}/${event.id}/${event.starts[index].id}`;
const row=id=>page.locator(`.mobile-event[data-entry-id="${id}"]`);
const search=()=>page.getByRole('textbox',{name:'搜索赛事',exact:true});
const choose=async(id,status)=>{await row(id).locator('.class-option').filter({hasText:new RegExp('^'+status+'$')}).click();};
const nav=async name=>{await page.locator('.bottom-nav').getByRole('button',{name:name==='我的自选'?/我的自选/:name,exact:true}).click();};
const select=async(label,name)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name,exact:true}).click();};
const fits=async locator=>{assert.equal(await locator.evaluate(element=>element.scrollWidth>element.clientWidth+1),false);};
const hashValue=key=>new URLSearchParams(new URL(page.url()).hash.slice(1)).get(key);
const matchingStarts=(currency,predicate)=>data.filter(event=>event.currency===currency).flatMap(event=>event.starts.filter(slot=>predicate(slot,event)).map(slot=>`${series}/${event.id}/${slot.id}`));
const checkFilter=async expected=>{
 assert.ok(expected.length>0);assert.match(await page.locator('.results-bar').innerText(),new RegExp(`找到\\s*${expected.length}\\s*个场次`));
 const shown=await page.locator('.mobile-event').evaluateAll(nodes=>nodes.map(node=>node.dataset.entryId));
 assert.ok(shown.length>0);assert.ok(shown.every(id=>expected.includes(id)),JSON.stringify(shown));
};
try{
 await page.goto(file+'#view=home&region=apac');await page.locator(`.festival-card[data-series-id="${series}"]`).click();
 await row(entry(opening)).waitFor();assert.match(await page.locator('.results-bar').innerText(),/86.*场次.*73.*赛事/s);
 assert.match(await page.locator('.series-header').innerText(),/KST/);assert.match(await row(entry(opening)).innerText(),/#1 ·/);
 assert.match(await row(entry(opening)).innerText(),/₩800,000（≈¥3,966.40）/);await choose(entry(opening),'关注');
 await row(entry(opening)).locator('.event-title').click();assert.match(await page.locator('.detail').innerText(),/10\/10 15:25 · KST/);
 assert.equal(await page.getByRole('link',{name:'官网本场赛程 ↗'}).getAttribute('href'),opening.starts[0].sourceUrl);
 await search().fill(opening.id);await row(entry(opening,2)).waitFor();assert.match(await row(entry(opening,2)).innerText(),/20:15/);
 await row(entry(opening,2)).locator('.event-title').click();assert.match(await page.locator('.detail').innerText(),/10\/10 22:30 · KST/);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(output,'discovery-390.png')});
 pass('KPC opens the verified 86 starts and 73 events with official numbers, exact minute times, Korean amounts and local deadlines');

 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await select('报名费筛选','₩500,000 及以下 · KRW');
 assert.equal(hashValue('buyin'),'KRW:500000');await checkFilter(matchingStarts('KRW',(slot,event)=>(slot.buyin??event.buyin)<=500000));
 await page.reload();assert.match(await page.getByRole('combobox',{name:'报名费筛选',exact:true}).innerText(),/₩500,000.*KRW/);
 await select('报名费筛选','$5,000 及以下 · USD');assert.equal(hashValue('buyin'),'USD:5000');
 await checkFilter(matchingStarts('USD',(slot,event)=>(slot.buyin??event.buyin)<=5000));
 await select('报名费筛选','全部报名费');await select('保底筛选','₩300,000,000 及以上 · KRW');
 assert.equal(hashValue('gtd'),'KRW:300000000');await checkFilter(matchingStarts('KRW',(_slot,event)=>(event.guarantee||0)>=300000000));
 await page.setViewportSize({width:320,height:900});await fits(page.locator('html'));await fits(page.locator('.mobile-event').first());
 await page.screenshot({path:resolve(output,'native-filter-320.png')});
 pass('mixed-series native buy-in and guarantee filters isolate KRW and USD, retain explicit currency on reload and fit 320px');

 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await search().fill(official(63).id);
 await select('赛事类型','德州扑克正赛');assert.equal(await page.locator('.mobile-event').count(),0);
 await select('赛事类型','PLO / 混合游戏');assert.equal(await page.locator('.mobile-event').count(),1);assert.match(await page.locator('.mobile-event').innerText(),/NLH \/ PLO MIXED/);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await select('赛事类型','卫星赛');
 assert.match(await page.locator('.results-bar').innerText(),/8.*场次.*8.*赛事/s);
 assert.deepEqual(await page.locator('.mobile-event .flight-tag').allInnerTexts(),Array(8).fill('首轮'));
 pass('NLH/PLO mixed games stay out of the NLH filter and all eight satellite entries retain their own first-round stage');

 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await search().fill(main.id);
 assert.equal(await page.locator('.mobile-event').count(),6);assert.match(await row(entry(main)).innerText(),/13:30/);
 assert.equal(await row(entry(main,2)).locator('.flight-tag').innerText(),'Day 1C Turbo');
 await choose(entry(main),'参加');await choose(entry(main,1),'参加');await nav('我的日程');
 const finals=page.locator(`.agenda-row[data-activity-id^="${series}/${main.id}/continuation/"]`);
 assert.equal(await finals.count(),2);assert.deepEqual(await finals.evaluateAll(nodes=>nodes.map(node=>node.dataset.status)),['attend','attend']);
 assert.equal(await page.locator('.agenda-row').count(),2+main.continuations.length+1+opening.continuations.length);
 assert.equal(await page.locator('.agenda-row[data-status="skip"],.agenda-row[data-status="undecided"]').count(),0);
 const calendar=page.locator('.schedule-calendar-panel');assert.equal(await calendar.getByRole('button',{name:/^2026年10月9日/}).isDisabled(),true);
 assert.equal(await calendar.getByRole('button',{name:/^2026年10月22日/}).isDisabled(),true);
 await calendar.getByRole('button',{name:/^2026年10月16日/}).click();assert.equal(await page.locator('.agenda-row').count(),1);
 await page.reload();await finals.waitFor();assert.match(await page.locator('.schedule-calendar-top').innerText(),/10\/10.*10\/21.*KST/);
 await finals.click();assert.match(await page.locator('.agenda-detail-sheet').innerText(),/晋级后/);assert.match(await page.locator('.agenda-detail-sheet').innerText(),/10\/16 13:00 · KST/);
 assert.equal(await page.locator('.agenda-detail-actions .classification').count(),0);await fits(page.locator('.agenda-detail-sheet'));
 await page.screenshot({path:resolve(output,'main-final-320.png')});await page.keyboard.press('Escape');await page.locator('.agenda-detail-sheet').waitFor({state:'hidden'});
 pass('two main-event flights produce only two conditional continuations, with KST calendar bounds and persistent final-day details');

 await page.goto(file+`#view=discover&series=${series}`);await search().fill(usdEvent.id);await row(entry(usdEvent)).waitFor();
 assert.match(await row(entry(usdEvent)).innerText(),/\$5,000/);assert.match(await row(entry(usdEvent)).innerText(),/12:30/);await choose(entry(usdEvent),'参加');
 await nav('我的自选');await page.getByRole('heading',{name:'我的自选',exact:true}).waitFor();
 assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩2,600,000（≈¥12,890.80）');
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/^\$5,000（≈¥/);
 assert.equal(await page.locator('.shortlist-table tr[data-entry-id]').count(),4);await fits(page.locator('.my-shortlist'));
 assert.ok(await page.locator('.shortlist-table-scroll').evaluate(element=>element.scrollWidth>element.clientWidth),'The full KPC table scrolls within the phone viewport');
 await page.screenshot({path:resolve(output,'mixed-native-budget-320.png')});
 await select('预算计算方式','同一赛事只算一次');assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩1,300,000（≈¥6,445.40）');
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/^\$5,000（≈¥/);
 pass('one KPC shortlist keeps KRW and USD budgets separate, excludes watched entries and charges no extra continuation buy-ins');

 await page.goto(file+'#view=discover&series=wpt-wynn-2026');const wpt='wpt-wynn-2026/W01/R0';await row(wpt).waitFor();await choose(wpt,'参加');
 await nav('我的自选');assert.equal(await page.locator('.shortlist-table tr[data-entry-id]').count(),5);
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/^\$5,600（≈¥/);
 assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩1,300,000（≈¥6,445.40）');
 await page.setViewportSize({width:390,height:950});await page.screenshot({path:resolve(output,'cross-series-budget-390.png')});
 await nav('我的');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出备份',exact:true}).click();
 const backup=resolve(output,'mixed-backup.json');await(await pending).saveAs(backup);
 await page.goto(file+`#view=discover&series=${series}`);await search().fill(main.id);await choose(entry(main),'不考虑');
 await page.getByLabel('选择备份文件').setInputFiles(backup);await page.getByRole('button',{name:'确认恢复',exact:true}).click();
 await page.waitForFunction(id=>document.querySelector(`.mobile-event[data-entry-id="${id}"]`)?.dataset.status==='attend',entry(main));
 await search().fill(opening.id);assert.equal(await row(entry(opening)).getAttribute('data-status'),'watch');
 await nav('我的自选');assert.equal(await page.locator('.shortlist-table tr[data-entry-id]').count(),5);
 assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩1,300,000（≈¥6,445.40）');
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/^\$5,600（≈¥/);
 pass('v2 backups restore KPC UUID selections, watch state, budget mode and cross-series USD totals entirely offline');

 await nav('我的');await page.getByRole('button',{name:/管理后台/}).click();
 await page.getByRole('tab',{name:'赛事管理',exact:true}).click();
 await page.getByRole('textbox',{name:'搜索管理赛事',exact:true}).fill(usdEvent.id);
 await page.getByRole('button',{name:`编辑 ${usdEvent.title}`,exact:true}).click();
 assert.match(await page.locator('.event-editor-sheet').innerText(),/统一报名费 · USD/);
 assert.match(await page.locator('.event-editor-sheet').innerText(),/赛事保底 · USD/);
 await page.getByRole('button',{name:'关闭赛事编辑',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await page.getByRole('tab',{name:'汇率设置',exact:true}).click();
 assert.equal(await page.getByRole('textbox',{name:'韩元汇率',exact:true}).inputValue(),'4.958');
 await page.getByRole('textbox',{name:'韩元汇率',exact:true}).fill('');await page.getByRole('button',{name:'保存汇率',exact:true}).click();
 await page.reload();
 assert.equal(await page.getByRole('textbox',{name:'韩元汇率',exact:true}).inputValue(),'');
 await nav('我的自选');assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩1,300,000（汇率未设置）');
 await nav('我的');await page.getByRole('button',{name:/管理后台/}).click();await page.getByRole('tab',{name:'汇率设置',exact:true}).click();
 // The editor quotes CNY per 1,000 KRW; this synthetic input sets the underlying rate to 0.0049.
 await page.getByRole('textbox',{name:'韩元汇率',exact:true}).fill('4.9');
 await page.getByRole('button',{name:'保存汇率',exact:true}).click();
 await page.reload();assert.equal(await page.getByRole('textbox',{name:'韩元汇率',exact:true}).inputValue(),'4.9');
 await nav('我的自选');assert.equal(await page.locator('.cart-budget [data-currency="KRW"]').innerText(),'₩1,300,000（≈¥6,370.00）');
 await fits(page.locator('html'));
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 pass('KPC dollar-event management retains USD units; KRW rate editing persists and updates only the matching native budget conversion');
}finally{
 await page.screenshot({path:resolve(output,'last-state.png')});await fs.writeFile(resolve(output,'results.json'),JSON.stringify({checks,errors,requests},null,2));await browser.close();
}
