import {chooseDiscoveryStatus,selectPlannerOption,openDiscoveryFilters,finishDiscoveryFilters} from './discovery-actions.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
const out=resolve('.sites-runtime/qa/profile-admin');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:950},offline:true,reducedMotion:'reduce'}),page=await context.newPage();
page.setDefaultTimeout(12000);
const errors=[],requests=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
const pass=s=>{checks.push(s);console.log('PASS',s);};
const file=pathToFileURL(resolve('release/WPT赛事自选表.html')).href;
const data=JSON.parse(await fs.readFile('lib/qpc-circuit-2026.json','utf8')),blast=data.find(e=>e.id==='QPC01');
const row=()=>page.locator(`.mobile-event[data-entry-id="qpc-circuit-2026/QPC01/${blast.starts[0].id}"]`);
const nav=name=>page.locator('.bottom-nav').getByRole('button',{name,exact:true}).click();
const select=(label,value)=>selectPlannerOption(page,label,value);
const discover=async()=>{await nav('赛事');await page.getByRole('link',{name:'查看 QPC Circuit 2026 完整赛程',exact:true}).click();};
const manage=async()=>{await nav('我的');await page.getByRole('button',{name:/管理后台/}).click();};
const failWrites=()=>page.evaluate(()=>{window.originalSettingWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});
const allowWrites=()=>page.evaluate(()=>{Storage.prototype.setItem=window.originalSettingWrite;});
const fits=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
try{
 await page.goto(file+'#view=discover&series=qpc-circuit-2026');await row().waitFor();
 assert.match(await page.locator('.mobile-event').first().innerText(),/₫900,000\s*（≈¥232.20）/);assert.match(await page.locator('.mobile-event').first().innerText(),/15 席/);
 assert.equal(await page.locator('.bottom-nav button').count(),4);assert.equal(await page.getByRole('button',{name:'赛程筛选',exact:true}).count(),1);assert.equal(await page.locator('.discovery-filter-popover').count(),0);
 await openDiscoveryFilters(page);const filterText=await page.locator('.discovery-filter-popover').innerText();assert.doesNotMatch(filterText,/显示分类|可多选|低买入/);await finishDiscoveryFilters(page);
 assert.equal(await page.getByRole('button',{name:'导出备份',exact:true}).count(),0);assert.doesNotMatch(await page.locator('.schedule-panel').innerText(),/个可报名场次/);
 await chooseDiscoveryStatus(page,row(),'参加');await openDiscoveryFilters(page);await page.screenshot({path:resolve(out,'filters-390.png')});await finishDiscoveryFilters(page);
 pass('four navigation items, on-demand filter dropdown, removed helper copy and native price with parenthesized conversion');
 await nav('我的');await page.getByLabel('用户名',{exact:true}).fill('小邵');await page.getByLabel('用户名',{exact:true}).dispatchEvent('compositionstart');await page.locator('.profile-name-form').dispatchEvent('submit');assert.doesNotMatch(await page.locator('.profile-identity').innerText(),/小邵/);await page.getByLabel('用户名',{exact:true}).dispatchEvent('compositionend');await page.getByRole('button',{name:'保存',exact:true}).click();
 assert.match(await page.locator('.profile-identity').innerText(),/小邵.*VIP 0/s);assert.match(await page.locator('.settings-facts').innerText(),/未登录/);
 await select('显示货币','越南盾 · VND');await page.reload();assert.equal(await page.getByLabel('用户名',{exact:true}).inputValue(),'小邵');
 assert.match(await page.getByRole('combobox',{name:'显示货币',exact:true}).innerText(),/越南盾/);
 await discover();assert.equal(await row().locator('.converted-price').count(),0);
 await nav('我的');await select('显示货币','美元 · USD');await discover();await select('赛事系列','WPT · Wynn 2026');
 assert.equal(await page.locator('.mobile-event .converted-price').count(),0);await select('赛事系列','QPC Circuit · 河内 2026');
 pass('username and preferred currency survive reload; same-currency entries never repeat a conversion');
 await nav('我的');await page.getByLabel('用户名',{exact:true}).fill('未保存草稿');await nav('赛事');
 await page.getByRole('alertdialog').waitFor();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.ok(page.url().includes('view=profile'));
 await nav('赛事');await page.getByRole('button',{name:'放弃修改',exact:true}).click();await nav('我的');assert.equal(await page.getByLabel('用户名',{exact:true}).inputValue(),'小邵');
 await page.getByLabel('用户名',{exact:true}).fill('返回前的草稿');await page.goBack();await page.getByRole('alertdialog').waitFor();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByLabel('用户名',{exact:true}).inputValue(),'返回前的草稿');await page.goBack();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.waitForURL(/view=home/);await nav('我的');
 await failWrites();await select('显示货币','港币 · HKD');assert.match(await page.locator('.form-error').innerText(),/未能保存/);assert.match(await page.getByRole('combobox',{name:'显示货币',exact:true}).innerText(),/美元/);await allowWrites();
 pass('unsaved profile edits require an explicit discard; failed setting writes preserve the selected currency');
 await manage();await page.getByRole('textbox',{name:'美元汇率',exact:true}).fill('0');await page.getByRole('button',{name:'保存汇率',exact:true}).click();assert.match(await page.locator('.form-error').innerText(),/大于零/);
 assert.equal(await page.getByRole('textbox',{name:'美元汇率',exact:true}).evaluate(e=>e===document.activeElement),true);
 await page.getByRole('textbox',{name:'美元汇率',exact:true}).fill('7');await page.getByRole('textbox',{name:'越南盾汇率',exact:true}).fill('0.25');await page.getByRole('textbox',{name:'港币汇率',exact:true}).fill('0.875');await page.getByLabel('来源或备注',{exact:true}).fill('测试规划汇率');
 await page.getByRole('button',{name:'保存汇率',exact:true}).click();assert.match(await page.locator('.source-caption').innerText(),/测试规划汇率/);await page.screenshot({path:resolve(out,'rates-390.png')});
 await discover();assert.match(await page.locator('.mobile-event').first().innerText(),/₫900,000\s*（≈\$32.14）/);
 await nav('我的');await select('显示货币','人民币 · CNY');await discover();assert.match(await page.locator('.mobile-event').first().innerText(),/₫900,000\s*（≈¥225.00）/);
 pass('manual rate validation, 1000-VND unit normalization and cross-rate calculation update all entry displays immediately');
 await manage();await page.getByRole('tab',{name:'赛事管理',exact:true}).click();await page.getByRole('textbox',{name:'搜索管理赛事',exact:true}).fill('QPC01');await page.locator('.admin-event-row').click();
 await page.getByLabel('赛事名称',{exact:true}).fill('QPC BLASTOFF · 本机编辑');await page.getByLabel('赛事报名费',{exact:true}).fill('5000000');await page.getByLabel('赛事保底金额',{exact:true}).fill('8000000000');await page.getByLabel('管理备注',{exact:true}).fill('核对后的本机备注');
 await failWrites();await page.getByRole('button',{name:'保存赛事',exact:true}).click();assert.match(await page.locator('.event-editor-sheet .form-error').innerText(),/未能保存/);await allowWrites();
 await page.getByRole('button',{name:'保存赛事',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('events-pro-settings-v1')).eventOverrides.QPC01.adminNotes),'核对后的本机备注');await page.locator('.admin-event-row').click();assert.equal(await page.getByLabel('管理备注',{exact:true}).inputValue(),'核对后的本机备注');
 await page.getByRole('checkbox',{name:'在赛事发现中显示',exact:true}).uncheck();await page.getByRole('button',{name:'保存赛事',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await page.screenshot({path:resolve(out,'events-390.png')});await discover();await page.getByRole('textbox',{name:'搜索赛事',exact:true}).fill('QPC01');assert.equal(await page.locator('.mobile-event').count(),0);
 await nav('我的日程');assert.equal(await page.locator('.agenda-row').count(),2);assert.match(await page.locator('.agenda-row').first().innerText(),/本机编辑/);
 await page.locator('.bottom-nav').getByRole('button',{name:/我的自选/}).click();assert.match(await page.locator('.cart-budget').innerText(),/₫5,000,000.*¥1,250.00/s);const selected=page.locator('.shortlist-table tr[data-entry-id]').first();assert.match(await selected.innerText(),/本机编辑/);assert.match(await selected.locator('[data-column="buyin"]').innerText(),/₫5,000,000.*¥1,250.00/s);assert.match(await selected.locator('[data-column="budget"]').innerText(),/₫5,000,000.*¥1,250.00/s);
 pass('event editing persists title/buy-in/guarantee/notes; hidden events stay in existing selections, agenda and the updated budget');
 await manage();await page.getByRole('tab',{name:'赛事管理',exact:true}).click();await page.getByRole('textbox',{name:'搜索管理赛事',exact:true}).fill('QPC01');await page.locator('.admin-event-row').click();
 assert.match(await page.locator('.structure-placeholder').innerText(),/级别.*小盲.*前注.*时长/s);await page.screenshot({path:resolve(out,'event-editor-390.png')});
 await page.getByRole('button',{name:'恢复官方数据',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'取消',exact:true}).click();assert.equal(await page.getByLabel('赛事名称',{exact:true}).inputValue(),'QPC BLASTOFF · 本机编辑');
 await page.getByRole('button',{name:'恢复官方数据',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'恢复官方数据',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await discover();await row().waitFor();assert.equal(await row().getAttribute('data-status'),'attend');assert.match(await row().innerText(),/₫4,500,000\s*（≈¥1,125.00）/);
 pass('official-data restore is confirmed and reversible up to confirmation, retains selections, and exposes an honest future blind-structure frame');
 await nav('我的');const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出设置备份',exact:true}).click();const backupPath=resolve(out,'settings-backup.json');await(await download).saveAs(backupPath);
 await select('显示货币','仅显示原币');await page.getByLabel('选择设置备份文件').setInputFiles(backupPath);await page.getByRole('button',{name:'确认恢复设置',exact:true}).click();assert.match(await page.getByRole('combobox',{name:'显示货币',exact:true}).innerText(),/人民币/);
 await manage();await page.getByRole('textbox',{name:'港币汇率',exact:true}).fill('');await page.getByRole('button',{name:'保存汇率',exact:true}).click();await nav('我的');await select('显示货币','港币 · HKD');await discover();assert.match(await row().innerText(),/汇率未设置/);assert.doesNotMatch(await row().innerText(),/HK\$0/);
 await nav('我的');await page.getByLabel('选择设置备份文件').setInputFiles(backupPath);await page.getByRole('button',{name:'确认恢复设置',exact:true}).click();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:950});await fits();await page.screenshot({path:resolve(out,`profile-${width}.png`)});}
 await page.setViewportSize({width:320,height:950});await manage();await fits();await page.getByRole('tab',{name:'赛事管理',exact:true}).click();await page.locator('.admin-event-row').first().click();assert.equal(await page.locator('.event-editor-sheet').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await page.getByRole('button',{name:'关闭赛事编辑',exact:true}).click();await page.locator('.event-editor-sheet').waitFor({state:'hidden'});
 await manage();await page.getByRole('textbox',{name:'美元汇率',exact:true}).fill('8');
 await page.evaluate(()=>{const key='events-pro-settings-v1',next=JSON.parse(localStorage.getItem(key));next.revision++;next.fx.rates.USD=9;localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new StorageEvent('storage',{key,newValue:JSON.stringify(next)}));});
 await page.getByRole('button',{name:'保存汇率',exact:true}).click();assert.match(await page.locator('.form-error').innerText(),/另一窗口/);assert.equal(await page.getByRole('textbox',{name:'美元汇率',exact:true}).inputValue(),'8');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('events-pro-settings-v1')).fx.rates.USD),9);
 await page.getByRole('button',{name:'重新载入',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:'美元汇率',exact:true}).inputValue(),'9');await nav('我的');
 await page.evaluate(()=>{const key='events-pro-settings-v1';localStorage.setItem(key,'{broken');window.dispatchEvent(new StorageEvent('storage',{key,newValue:'{broken'}));});await page.getByRole('alert').filter({hasText:'无法读取个人'}).waitFor();assert.equal(await page.getByRole('combobox',{name:'显示货币',exact:true}).isDisabled(),true);
 await page.getByLabel('选择设置备份文件').setInputFiles(backupPath);await page.getByRole('button',{name:'确认恢复设置',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'显示货币',exact:true}).isDisabled(),false);
 pass('stale editor saves preserve both the newer record and draft; validated settings backup recovers a corrupt local record');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);pass('settings backup/restore, missing-rate handling, responsive profile/admin forms and entirely offline operation');
}finally{await page.screenshot({path:resolve(out,'last-state.png')});await fs.writeFile(resolve(out,'results.json'),JSON.stringify({checks,errors,requests},null,2));await browser.close();}
