import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
const output=resolve('.sites-runtime/qa/qpc');await fs.mkdir(output,{recursive:true});
const data=JSON.parse(await fs.readFile('lib/qpc-circuit-2026.json','utf8'));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:950},offline:true,reducedMotion:'reduce'});
const page=await context.newPage(),checks=[],errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
const pass=name=>{checks.push(name);console.log('PASS',name);};
const file=pathToFileURL(resolve('release/WPT赛事自选表.html')).href,series='qpc-circuit-2026';
const entry=(event,index=0)=>`${series}/${event}/${data.find(e=>e.id===event).starts[index].id}`;
const row=id=>page.locator(`.mobile-event[data-entry-id="${id}"]`);
const search=()=>page.getByRole('textbox',{name:'搜索赛事',exact:true});
const choose=async(id,status)=>{await row(id).locator('.class-option').filter({hasText:new RegExp('^'+status+'$')}).click();};
const nav=async name=>{await page.locator('.bottom-nav').getByRole('button',{name:name==='我的自选'?/我的自选/:name,exact:true}).click();};
const select=async(label,name)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name,exact:true}).click();};
const closeCart=async()=>{await page.getByRole('button',{name:'关闭我的自选',exact:true}).click();await page.locator('.cart-sheet').waitFor({state:'hidden'});};
const fits=async locator=>{assert.equal(await locator.evaluate(e=>e.scrollWidth>e.clientWidth+1),false);};
try{
 await page.goto(file+'#view=home&region=apac');await page.locator(`.festival-card[data-series-id="${series}"]`).click();
 await row(entry('QPC01')).waitFor();assert.match(await page.locator('.results-bar').innerText(),/91.*场次.*77.*赛事/s);
 assert.match(await page.locator('.series-header').innerText(),/ICT/);assert.match(await row(entry('QPC01')).innerText(),/10:30/);
 assert.match(await row(entry('QPC01')).innerText(),/₫4,500,000/);await choose(entry('QPC01'),'关注');
 await row(entry('QPC01')).locator('.event-title').click();assert.match(await page.locator('.detail').innerText(),/10\/12 16:35 · ICT/);
 assert.equal(await page.getByRole('link',{name:'官网本场赛程 ↗'}).getAttribute('href'),data.find(e=>e.id==='QPC01').starts[0].sourceUrl);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(output,'discovery-390.png')});
 pass('APAC card opens all QPC flights with VND amounts, half-hour starts, ICT deadlines and the exact source link');
 await select('报名费筛选','450万₫及以下');assert.ok(page.url().includes('buyin=4500000'));await page.reload();
 assert.match(await page.getByRole('combobox',{name:'报名费筛选',exact:true}).innerText(),/450万₫/);
 await select('保底筛选','10亿₫及以上');assert.match(await page.locator('.results-bar').innerText(),/9.*场次.*2.*赛事/s);
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await select('赛事类型','卫星赛');
 assert.match(await page.locator('.results-bar').innerText(),/19.*场次.*19.*赛事/s);assert.match(await page.locator('.mobile-event').first().innerText(),/15 席/);
 assert.doesNotMatch(await page.locator('.mobile-event').first().innerText(),/QPCS-/);
 await page.setViewportSize({width:320,height:900});await fits(page.locator('.mobile-event').first());await fits(page.locator('html'));
 await page.getByRole('button',{name:'重置筛选',exact:true}).click();await search().fill('#31');
 await page.locator('.mobile-event .event-title').click();assert.match(await page.locator('.detail').innerText(),/未标日期/);
 await page.locator('.detail').scrollIntoViewIfNeeded();await page.screenshot({path:resolve(output,'ambiguous-deadline-320.png')});
 await search().fill('QPC47');await row(entry('QPC47',2)).locator('.event-title').click();assert.match(await page.locator('.detail').innerText(),/10\/21 00:40 · ICT/);
 pass('native VND filters persist on reload; satellites retain ticket guarantees and deadline anomalies remain visible');
 await search().fill('QPC30');assert.equal(await page.locator('.mobile-event').count(),5);
 await choose(entry('QPC30'),'参加');await choose(entry('QPC30',1),'参加');await nav('我的日程');
 const finals=page.locator(`.agenda-row[data-activity-id^="${series}/QPC30/continuation/"]`);
 assert.equal(await finals.count(),2);assert.deepEqual(await finals.evaluateAll(nodes=>nodes.map(n=>n.dataset.status)),['attend','attend']);
 assert.equal(await page.locator('.agenda-row').count(),6);
 const cal=page.locator('.schedule-calendar-panel');assert.equal(await cal.getByRole('button',{name:/^2026年10月11日/}).isDisabled(),true);
 assert.equal(await cal.getByRole('button',{name:/^2026年10月22日/}).isDisabled(),true);
 await cal.getByRole('button',{name:/^2026年10月21日/}).click();assert.equal(await page.locator('.agenda-row').count(),1);
 await page.reload();await finals.waitFor();assert.match(await page.locator('.schedule-calendar-top').innerText(),/10\/12.*10\/21.*ICT/);
 await finals.click();assert.match(await page.locator('.agenda-detail-sheet').innerText(),/晋级后/);assert.equal(await page.locator('.agenda-detail-actions .classification').count(),0);
 await fits(page.locator('.agenda-detail-sheet'));await page.screenshot({path:resolve(output,'main-final-320.png')});await page.keyboard.press('Escape');
 await page.locator('.agenda-detail-sheet').waitFor({state:'hidden'});
 pass('selected flights create deduplicated conditional finals, bounded QPC calendar and persistent final-day detail');
 await page.goto(file+'#view=discover&series=wpt-wynn-2026');const wpt='wpt-wynn-2026/W01/R0';await row(wpt).waitFor();await choose(wpt,'参加');
 await nav('我的自选');await page.locator('.cart-sheet').waitFor();
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/\$600.*¥4,041.06/);
 assert.equal(await page.locator('.cart-budget [data-currency="VND"]').innerText(),'₫22,000,000（≈¥5,676.00）');
 assert.equal(await page.locator('.cart-entry').count(),4);await fits(page.locator('.cart-sheet'));
 for(const item of await page.locator('.cart-entry').all())await fits(item);
 await page.screenshot({path:resolve(output,'mixed-budget-320.png')});
 await select('预算计算方式','同一赛事只算一次');assert.equal(await page.locator('.cart-budget [data-currency="VND"]').innerText(),'₫11,000,000（≈¥2,838.00）');
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/\$600/);
 await page.setViewportSize({width:390,height:950});await page.screenshot({path:resolve(output,'mixed-budget-390.png')});await closeCart();
 pass('mixed WPT/QPC shortlist shows separate USD and VND totals, excludes watched flights and applies both budget modes');
 await nav('我的');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出备份',exact:true}).click();
 const backup=resolve(output,'mixed-backup.json');await(await pending).saveAs(backup);await nav('赛事');await page.getByRole('link',{name:'查看 WPT World Championship 2026 完整赛程',exact:true}).click();await choose(wpt,'不考虑');
 await page.getByLabel('选择备份文件').setInputFiles(backup);await page.getByRole('button',{name:'确认恢复',exact:true}).click();
 await page.waitForFunction(id=>document.querySelector(`.mobile-event[data-entry-id="${id}"]`)?.dataset.status==='attend',wpt);
 await select('赛事系列','QPC Circuit · 河内 2026');await row(entry('QPC01')).waitFor();assert.equal(await row(entry('QPC01')).getAttribute('data-status'),'watch');
 await nav('我的自选');assert.equal(await page.locator('.cart-budget [data-currency="VND"]').innerText(),'₫11,000,000（≈¥2,838.00）');
 assert.match(await page.locator('.cart-budget [data-currency="USD"]').innerText(),/\$600/);await closeCart();
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(requests.length,0,requests.join('\n'));
 pass('mixed-series v2 backup restores original selections and budget mode, entirely offline without browser errors');
}finally{await page.screenshot({path:resolve(output,'last-state.png')});await fs.writeFile(resolve(output,'results.json'),JSON.stringify({checks,errors,requests},null,2));await browser.close();}
