import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'vite';
const output='.sites-runtime/qpc-unit';
await build({configFile:false,logLevel:'error',build:{outDir:output,emptyOutDir:true,minify:false,lib:{entry:Object.fromEntries(['catalog','schedule','money','agenda','local-store'].map(name=>[name,resolve(`lib/${name}.ts`)])),formats:['es'],fileName:(_format,name)=>name+'.js'}}});
const module=async name=>import(pathToFileURL(resolve(output,name+'.js')).href);
const [{entries,eventMap,seriesList,validDate},{events,clock,slotName,guarantee},{money,moneyFilters},{agendaActivities,agendaFromUrl},{budget,emptyState,parseBackup,makeBackup}]=await Promise.all(['catalog','schedule','money','agenda','local-store'].map(module));
const series='qpc-circuit-2026',festival=seriesList.find(s=>s.id===series),qpc=events.filter(e=>e.seriesId===series);
const snapshot=JSON.parse(readFileSync('sources/qpc-circuit-2026.snapshot.json','utf8'));
assert.equal(qpc.length,77);assert.equal(qpc.filter(e=>e.kind==='satellite').length,19);
assert.deepEqual(qpc.filter(e=>e.officialNumber).map(e=>e.officialNumber),Array.from({length:58},(_,i)=>i+1));
const starts=qpc.flatMap(e=>e.starts),continuations=qpc.flatMap(e=>e.continuations);
assert.equal(starts.length,91);assert.equal(continuations.length,9);
assert.equal(new Set(events.map(e=>e.id)).size,events.length);assert.equal(new Set(entries.map(e=>e.id)).size,entries.length);
assert.equal(snapshot.rows.length,100);assert.equal(new Set(snapshot.rows.map(r=>r.sourceId)).size,100);
for(const row of snapshot.rows){
 const event=qpc.find(e=>[...e.starts,...e.continuations].some(s=>s.id===row.sourceId));assert.ok(event);
 const slot=(row.continuation?event.continuations:event.starts).find(s=>s.id===row.sourceId);assert.ok(slot);
 assert.equal(event.currency,'VND');assert.equal(event.buyin,row.buyinVnd);assert.equal(slot.date,row.date);assert.equal(clock(slot.hour),row.time);
 assert.equal(slot.sourceUrl,row.sourceUrl);assert.equal(slot.levels,row.levelMinutes.join('/'));
 assert.equal(slot.buyin,row.continuation?null:row.buyinVnd);assert.equal(slot.chips,row.continuation?null:row.startingStack);
 if(!row.continuation){assert.equal(event.guarantee,row.guaranteeVnd);assert.equal(slot.count,row.guaranteedTickets);}
}
assert.deepEqual(snapshot.rows.reduce((counts,row)=>(counts[Number(row.date.slice(-2))-12]++,counts),Array(10).fill(0)),[9,11,11,10,10,9,11,9,11,9]);
console.log('PASS all 100 QPC source occurrences reconcile to 77 events, 91 starts and nine continuations; exact VND amounts, chips, durations and source links');
const blast=eventMap.get('QPC01'),main=eventMap.get('QPC30'),imperial=eventMap.get('QPC47');
assert.equal(blast.starts.length,6);assert.equal(blast.continuations.length,1);assert.match(blast.continuations[0].name,/Kick Off/);
assert.equal(main.starts.length,5);assert.deepEqual(main.continuations.map(s=>s.date),['2026-10-20','2026-10-21']);
assert.equal(imperial.starts[2].registrationCloses,'2026-10-21T00:40');
assert.equal(eventMap.get('QPC31').starts[0].registrationCloses,undefined);assert.match(eventMap.get('QPC31').starts[0].notes,/未标日期/);
assert.equal(slotName(blast.starts[0]),'Day 1A');assert.equal(clock(10.5),'10:30');assert.equal(clock(11),'11:00');
assert.equal(money(4500000,'VND'),'₫4,500,000');assert.equal(guarantee(main),'₫10,000,000,000');
assert.equal(guarantee(qpc.find(e=>e.kind==='satellite')),'15 席');
assert.ok(moneyFilters('VND').buyin.slice(1).every(([,label])=>label.includes('₫')));
console.log('PASS fractional hours, flight labels, next-day deadline, ambiguous #31 deadline, cash guarantees and satellite ticket guarantees');
const state=emptyState(),planned=entries.filter(e=>e.eventId==='QPC30').slice(0,2);
for(const e of planned)state.selections[e.id]={status:'attend',version:1};
state.selections['wpt-wynn-2026/W01/R0']={status:'attend',version:1};
state.selections['triton-one-cyprus-2026/T12/T12-D1A']={status:'watch',version:1};
assert.deepEqual(budget(state).totals,{VND:22000000,USD:600});assert.equal(budget(state).total,600);assert.equal(budget(state).totalCurrency,'USD');
state.budgetMode='events';assert.deepEqual(budget(state).totals,{VND:11000000,USD:600});
state.pending.QPC01={status:'attend',version:1};assert.equal(budget(state).totals.VND,15500000);
assert.deepEqual(parseBackup(JSON.stringify(makeBackup(state))).state,state);
const activities=agendaActivities(state,false,series);assert.equal(activities.length,100);
const finals=activities.filter(a=>a.event.id==='QPC30'&&a.kind==='continuation');assert.equal(finals.length,2);assert.ok(finals.every(a=>a.status==='attend'&&a.buyin===0));
assert.ok(activities.every(a=>a.entry.currency==='VND'));assert.equal(agendaActivities(state).length,125);
assert.equal(validDate('2026-10-12',festival),true);assert.equal(validDate('2026-10-22',festival),false);
globalThis.window={location:{hash:`#series=${series}&view=schedule&day=2026-10-21&month=2026-11`}};
assert.equal(agendaFromUrl().day,'2026-10-21');assert.equal(agendaFromUrl().month,'2026-10');
console.log('PASS cross-currency budgets never add VND to USD; both budget modes, legacy pending, v2 backup, conditional continuation and QPC route boundaries');
