import assert from 'node:assert/strict';
import {build} from 'vite';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
await build({configFile:false,logLevel:'error',build:{outDir:'.sites-runtime/unit',emptyOutDir:true,minify:false,lib:{entry:resolve('lib/local-store.ts'),formats:['es'],fileName:'planner-store'}}});
const {parseBackup,emptyState,budget,readState,writeState,STORAGE_KEY,LEGACY_KEY}=await import(pathToFileURL(resolve('.sites-runtime/unit/planner-store.js')).href);
const checks=[];const pass=name=>{checks.push(name);console.log('PASS',name);};
const old=selections=>JSON.stringify({app:'wpt-planner',schemaVersion:1,savedAt:'2026-10-02T10:00:00Z',selections});
const id=slot=>`wpt-wynn-2026/W01/${slot}`;
const migrated=parseBackup(old({W01:{status:'attend',flight:'R4',version:2},W05:{status:'attend',flight:'',version:1},W02:{status:'watch',flight:'',version:0}})).state;
assert.equal(migrated.selections[id('R4')].status,'attend');assert.equal(migrated.selections[id('R0')],undefined);assert.equal(migrated.pending.W05.status,'attend');assert.equal(budget(migrated).total,1400);pass('v1 selected flight retained and unassigned attendance never multiplied');
const watching=parseBackup(old({W01:{status:'watch',flight:'',version:2}})).state;assert.equal(Object.keys(watching.selections).length,6);assert.ok(Object.values(watching.selections).every(s=>s.status==='watch'));pass('unassigned legacy watch expands to all six flights');
const selectedWatch=parseBackup(old({W01:{status:'watch',flight:'R3',version:1}})).state;assert.equal(Object.keys(selectedWatch.selections).length,1);assert.equal(selectedWatch.selections[id('R3')].status,'watch');pass('explicit old flight is not broadened');
const state=emptyState();state.selections[id('R0')]={status:'attend',version:1};state.selections[id('R3')]={status:'attend',version:1};state.pending.W05={status:'attend',version:1};assert.equal(budget(state).total,2000);state.budgetMode='events';assert.equal(budget(state).total,1400);assert.equal(budget(state).eventCount,2);pass('budget per-flight and per-event with pending attendance');
for(const source of [old({W01:{status:'attend',flight:'invalid',version:1}}),old({BAD:{status:'watch',flight:'',version:0}}),old({W01:{status:'invalid',flight:'R0',version:1}}),JSON.stringify({app:'wpt-planner',schemaVersion:3,savedAt:'2026-10-02T00:00:00Z'})])assert.throws(()=>parseBackup(source));pass('invalid flight, event, status and schema rejected');
const collision={...emptyState(),selections:{[id('R0')]:{status:'attend',version:1}},pending:{W01:{status:'attend',version:1}}};assert.throws(()=>parseBackup(JSON.stringify({app:'wpt-planner',schemaVersion:2,savedAt:'2026-10-02T10:00:00Z',state:collision})));pass('inconsistent pending and attending same event rejected');
const records=new Map([[LEGACY_KEY,old({W01:{status:'attend',flight:'',version:1}})]]);const legacy=records.get(LEGACY_KEY);globalThis.localStorage={getItem:key=>records.get(key)??null,setItem:(key,v)=>records.set(key,v)};const pending=readState();assert.equal(Object.keys(pending.pending).length,1);assert.equal(records.has(STORAGE_KEY),false);writeState(pending);assert.equal(records.get(LEGACY_KEY),legacy);assert.equal(readState().pending.W01.status,'attend');pass('v1 migration does not erase legacy raw record');
globalThis.localStorage.setItem=()=>{throw new Error('Full');};assert.throws(()=>writeState(emptyState()),/未能保存/);assert.equal(readState().pending.W01.status,'attend');pass('failed write preserves disk state');
console.log(`${checks.length} state checks passed`);
