import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
const output=resolve('.sites-runtime/qa/triton');await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:950},offline:true});
const page=await context.newPage(),checks=[],errors=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
const pass=name=>{checks.push(name);console.log('PASS',name);};
const file=pathToFileURL(resolve('release/WPT赛事自选表.html')).href,series='triton-one-cyprus-2026';
const selector=()=>page.getByRole('combobox',{name:'赛事系列',exact:true});
const switchTo=async name=>{await selector().click();await page.getByRole('option',{name,exact:true}).click();};
const nav=async name=>{await page.locator('.bottom-nav').getByRole('button',{name:name==='我的自选'?/我的自选/:name==='赛事发现'?'赛事':name,exact:true}).click();if(name==='赛事发现')await page.getByRole('link',{name:'查看 WPT World Championship 2026 完整赛程',exact:true}).click();};
const row=id=>page.locator(`.mobile-event[data-entry-id="${id}"]`);
const select=async(id,status)=>{await row(id).locator('.class-option').filter({hasText:new RegExp('^'+status+'$')}).click();};
const first=`${series}/T01/T01-D1A`,wpt='wpt-wynn-2026/W01/R0';
try{
 await page.goto(file+'#view=discover&series=wpt-wynn-2026');await row(wpt).waitFor();await select(wpt,'参加');
 await page.getByRole('textbox',{name:'搜索赛事'}).fill('W01');
 await selector().focus();await page.keyboard.press('Enter');await page.getByRole('listbox').waitFor();await page.getByRole('option',{name:'WPT · Wynn 2026',exact:true}).focus();await page.keyboard.press('ArrowDown');await page.waitForFunction(()=>document.activeElement?.textContent?.includes('北塞浦路斯'));await page.keyboard.press('Enter');
 await row(first).waitFor();assert.ok(page.url().includes(`series=${series}`));
 assert.equal(await page.getByRole('textbox',{name:'搜索赛事'}).inputValue(),'');
 assert.match(await page.locator('.results-bar').innerText(),/29.*场次.*22.*赛事/s);
 assert.equal(await page.getByRole('checkbox',{name:'显示官方补充卫星',exact:true}).count(),0);
 await select(first,'参加');pass('keyboard series switch clears incompatible discovery filters and shows all 29 original flights');
 await page.locator('.mobile-event').first().getByRole('button',{name:'QQPK Genesis'}).click();
 assert.match(await page.locator('.detail').innerText(),/11\/05 19:25 · EET/);
 assert.match(await page.locator('.detail').innerText(),/250,000/);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(output,'discovery-390.png')});
 await page.setViewportSize({width:320,height:900});const trigger=await selector().boundingBox();await selector().click();
 await page.getByRole('listbox').evaluate(async element=>{await Promise.all(element.getAnimations().map(animation=>animation.finished));});
 const popup=await page.getByRole('listbox').boundingBox();
 assert.ok(Math.abs(trigger.width-popup.width)<=1,JSON.stringify({trigger,popup}));assert.ok(popup.x>=0&&popup.x+popup.width<=321);
 await page.screenshot({path:resolve(output,'series-popup-320.png')});await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:390,height:950});pass('shared series popup supports keyboard and fits a 320px phone; details show local deadlines');
 await page.getByRole('textbox',{name:'搜索赛事'}).fill('T06');
 await page.locator('.mobile-event .event-title').click();assert.match(await page.locator('.detail').innerText(),/仅限女性参赛/);
 await page.getByRole('textbox',{name:'搜索赛事'}).fill('T21');
 await page.locator('.mobile-event .event-title').click();
 assert.match(await page.locator('.detail').innerText(),/1,352.*500.*111.*37/s);
 assert.match(await page.locator('.detail').innerText(),/11\/13 00:30/);
 await page.locator('.detail').scrollIntoViewIfNeeded();await page.screenshot({path:resolve(output,'derived-buyin-detail.png')});
 pass('shared details preserve women-only eligibility, derived buy-in evidence, and next-day registration');
 await page.getByRole('textbox',{name:'搜索赛事'}).fill('#12');
 assert.equal(await page.locator('.mobile-event').count(),3);await select(`${series}/T12/T12-D1A`,'参加');await select(`${series}/T12/T12-D1B`,'参加');
 await nav('我的日程');const finals=page.locator(`.agenda-row[data-activity-id^="${series}/T12/continuation/"]`);
 assert.equal(await finals.count(),3);assert.deepEqual(await finals.evaluateAll(nodes=>nodes.map(n=>n.dataset.status)),['attend','attend','attend']);
 const cal=page.locator('.schedule-calendar-panel');
 assert.equal(await cal.getByRole('button',{name:/^2026年11月4日/}).isDisabled(),true);
 assert.equal(await cal.getByRole('button',{name:/^2026年11月16日/}).isDisabled(),true);
 await cal.getByRole('button',{name:/^2026年11月15日/}).click();
 assert.equal(await page.locator(`.agenda-row[data-activity-id="${series}/T12/continuation/2"]`).count(),1);
 assert.ok((await page.locator('.agenda-row').allTextContents()).every(s=>s.includes('晋级后')));
 await page.reload();await page.locator('.agenda-row').first().waitFor();
 assert.equal(await page.locator(`.agenda-row[data-activity-id="${series}/T12/continuation/2"]`).count(),1);
 assert.match(await selector().innerText(),/北塞浦路斯/);pass('Triton calendar enforces Nov 5–15, includes main final day, and restores series/day after reload');
 await page.getByRole('button',{name:'全部日期',exact:true}).click();
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(output,'agenda-390.png')});
 await switchTo('WPT · Wynn 2026');assert.equal(await page.locator(`.agenda-row[data-entry-id="${wpt}"]`).count(),1);
 assert.equal(await page.locator(`.agenda-row[data-activity-id^="${series}/"]`).count(),0);
 assert.match(await page.locator('.schedule-calendar-top').innerText(),/11\/27.*12\/21.*PST/);
 await nav('我的自选');await page.locator('.shortlist-table').waitFor();assert.equal(await page.locator('.shortlist-table tr[data-entry-id]').count(),4);assert.match(await page.locator('.cart-budget').innerText(),/\$19,600/);
 assert.match(await page.locator('.shortlist-table').innerText(),/Merit Royal Diamond/);
 assert.match(await page.locator('.shortlist-table').innerText(),/Wynn Las Vegas/);
 assert.match(await page.locator('.shortlist-table').innerText(),/EET/);assert.match(await page.locator('.shortlist-table').innerText(),/PST/);
 await page.getByRole('combobox',{name:'预算计算方式'}).click();await page.getByRole('option',{name:'同一赛事只算一次',exact:true}).click();
 assert.match(await page.locator('.cart-budget').innerText(),/\$11,600/);
 assert.ok(page.url().includes('view=shortlist'));assert.equal(await page.getByRole('dialog').count(),0);
 pass('main event creates three conditional days; cross-series shortlist and both budget modes retain original WPT selections');
 await nav('赛事发现');await row(wpt).waitFor();assert.equal(await row(wpt).getAttribute('data-status'),'attend');
 await switchTo('Triton ONE · 北塞浦路斯 2026');await row(first).waitFor();assert.equal(await row(first).getAttribute('data-status'),'attend');
 await nav('我的');const backupDownload=page.waitForEvent('download');await page.getByRole('button',{name:'导出备份',exact:true}).click();
 const backup=await backupDownload,backupPath=resolve(output,'cross-series.json');await backup.saveAs(backupPath);
 const saved=JSON.parse(await fs.readFile(backupPath,'utf8'));assert.equal(Object.keys(saved.state.selections).length,4);
 await nav('赛事发现');await switchTo('Triton ONE · 北塞浦路斯 2026');await select(first,'不考虑');await page.getByLabel('选择备份文件').setInputFiles(backupPath);
 await page.getByRole('button',{name:'确认恢复',exact:true}).click();
 await page.waitForFunction(id=>document.querySelector(`.mobile-event[data-entry-id="${id}"]`)?.dataset.status==='attend',first);
 pass('v2 export and restore round-trip selections from both festivals without a schema migration');
 const pdfDownload=page.waitForEvent('download');await page.getByRole('link',{name:'下载原始赛程 PDF'}).click();
 const pdf=await pdfDownload,pdfPath=resolve(output,'source.pdf');await pdf.saveAs(pdfPath);
 const digest=createHash('sha256').update(await fs.readFile(pdfPath)).digest('hex');
 assert.equal(digest,'c1c4f188999bd820f79ff6bb03817f50ccabee2de4e579c653c8cdad60561af2');
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(requests.length,0,requests.join('\n'));
 pass('original PDF downloads byte-for-byte from the offline single file; no HTTP requests or browser errors');
}finally{await page.screenshot({path:resolve(output,'last-state.png')});await fs.writeFile(resolve(output,'results.json'),JSON.stringify({checks,errors,requests},null,2));await browser.close();}
